name: Autograding

on: [push, pull_request]

jobs:
  run-autograder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install required packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "testthat"), repos = "https://cloud.r-project.org")'

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run autograder
        run: Rscript grade.R
